workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    environment:
      flutter: 3.44.0
      xcode: 16.0
      cocoapods: default
      vars:
        BUNDLE_ID: com.melicharek.susedko
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Pod install
        script: |
          cd ios
          pod install --clean-install
          cd ..
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

          # Uloz API key do suboru
          echo $APP_STORE_CONNECT_PRIVATE_KEY > /tmp/AuthKey.p8

          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            -authenticationKeyPath /tmp/AuthKey.p8 \
            -authenticationKeyID $APP_STORE_CONNECT_KEY_IDENTIFIER \
            -authenticationKeyIssuerID $APP_STORE_CONNECT_ISSUER_ID \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=SQ2VV7TA67 \
            archive
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            -exportOptionsPlist ../ios/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/ipa
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true