workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    environment:
      flutter: 3.44.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Pod install
        script: |
          cd ios
          pod install --clean-install
          find . -name "*.sh" -path "*/Pods/*" -exec chmod +x {} \;
          cd ..
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
          cp ios/AuthKey.p8 /tmp/AuthKey.p8
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            -authenticationKeyPath /tmp/AuthKey.p8 \
            -authenticationKeyID "S6JD8KBSNV" \
            -authenticationKeyIssuerID "08941c62-c68a-462c-9204-4dad33c5bcf0" \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=SQ2VV7TA67 \
            archive
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            -exportOptionsPlist ../ios/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/ipa \
            -allowProvisioningUpdates \
            -authenticationKeyPath /tmp/AuthKey.p8 \
            -authenticationKeyID "S6JD8KBSNV" \
            -authenticationKeyIssuerID "08941c62-c68a-462c-9204-4dad33c5bcf0"
      - name: Upload to TestFlight
        script: |
          app-store-connect publish \
            --path $CM_BUILD_DIR/ipa/susedko.ipa \
            --key-id "S6JD8KBSNV" \
            --issuer-id "08941c62-c68a-462c-9204-4dad33c5bcf0" \
            --private-key @file:/tmp/AuthKey.p8 \
            --testflight
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa