// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVIXnQay8r5WJJCz4vOPMBQawwJRXThgg',
    appId: '1:178095889465:android:1b979f3a8d81ab8d4601e8',
    messagingSenderId: '178095889465',
    projectId: 'myknife-58a1a',
    storageBucket: 'myknife-58a1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeGAjTb4EdavVOXYzf_I1ISs5e1N-1qR0',
    appId: '1:329689613080:ios:3de98939f0a9b05fe7146d',
    messagingSenderId: '329689613080',
    projectId: 'drone-guard-bdeaf',
    storageBucket: 'drone-guard-bdeaf.firebasestorage.app',
    iosClientId: '329689613080-uhokeseacqe2uleq01ocb11gjukcg41n.apps.googleusercontent.com',
    iosBundleId: 'com.melicharek.susedko',
  );
}
